export const POSTER_PATH = "https://image.tmdb.org/t/p/w370_and_h556_bestv2";

export const MOVIE_TITLES = [
  { title: "Title", data_item: "title", type: "string" },
  { title: "Vote", data_item: "vote_count", type: "interger" },
  { title: "Average Vote", data_item: "vote_average", type: "interger" },
  { title: "Popularity", data_item: "popularity", type: "interger" },
  { title: "Poster", data_item: "poster_path", type: "string" },
  { title: "Overview", data_item: "overview", type: "string" },
  { title: "Favorite", data_item: "favorite", type: "boolean" },
  { title: "Delete", data_item: "delete", type: "function" }
];

export const MOVIE_DATA = [
  {
    vote_count: 506,
    id: 37257,
    video: false,
    vote_average: 6.9,
    title: "Witness for the Prosecution",
    popularity: 7.613,
    poster_path: "/heY0CCUqN4DY3X30thssZkvWZwx.jpg",
    original_language: "en",
    original_title: "Witness for the Prosecution",
    genre_ids: [18, 9648, 80],
    backdrop_path: "/kazLzEofKKr7pBcvKw6VRtFnXRJ.jpg",
    adult: false,
    overview:
      "When Leonard Vole is arrested for the sensational murder of a rich, middle-aged widow, the famous Sir Wilfrid Robarts agrees to appear on his behalf. Sir Wilfrid, recovering from a near-fatal heart attack, is supposed to be on a diet of bland, civil suits—but the lure of the criminal courts is too much for him, especially when the case is so difficult.",
    release_date: "1957-12-17"
  },
  {
    vote_count: 269,
    id: 24382,
    video: false,
    vote_average: 6.8,
    title: "Big Deal on Madonna Street",
    popularity: 7.282,
    poster_path: "/f5OxD8Nl0pR3DcYHtYhHRfpsmjl.jpg",
    original_language: "it",
    original_title: "I soliti ignoti",
    genre_ids: [35, 80],
    backdrop_path: "/tzbBAsLzX3n0GcAK7KEwnSvlDrT.jpg",
    adult: false,
    overview:
      "Best friends Peppe and Mario are thieves, but they're not very good at it. Still, Peppe thinks that he's finally devised a master heist that will make them rich. With the help of some fellow criminals, he plans to dig a tunnel from a rented apartment to the pawnshop next door, where they can rob the safe. But his plan is far from foolproof, and the fact that no one in the group has any experience digging tunnels proves to be the least of their problems.",
    release_date: "1958-06-06"
  },
  {
    vote_count: 680,
    id: 455661,
    video: false,
    vote_average: 6.7,
    title: "In a Heartbeat",
    popularity: 5.942,
    poster_path: "/wJUJROdLOtOzMixkjkx1aaZGSLl.jpg",
    original_language: "en",
    original_title: "In a Heartbeat",
    genre_ids: [10751, 16, 10749, 35],
    backdrop_path: "/6DwR9kIUvsWq434d7NFLWroHTdI.jpg",
    adult: false,
    overview:
      "A closeted boy runs the risk of being outed by his own heart after it pops out of his chest to chase down the boy of his dreams.",
    release_date: "2017-06-01"
  },
  {
    vote_count: 2063,
    id: 19404,
    video: false,
    vote_average: 9,
    title: "Dilwale Dulhania Le Jayenge",
    popularity: 17.018,
    poster_path: "/uC6TTUhPpQCmgldGyYveKRAu8JN.jpg",
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    genre_ids: [35, 18, 10749],
    backdrop_path: "/nl79FQ8xWZkhL3rDr1v2RFFR6J0.jpg",
    adult: false,
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    release_date: "1995-10-20"
  },
  {
    vote_count: 13171,
    id: 278,
    video: false,
    vote_average: 8.7,
    title: "The Shawshank Redemption",
    popularity: 33.993,
    poster_path: "/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg",
    original_language: "en",
    original_title: "The Shawshank Redemption",
    genre_ids: [18, 80],
    backdrop_path: "/j9XKiZrVeViAixVRzCta7h1VU9W.jpg",
    adult: false,
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    release_date: "1994-09-23"
  },
  {
    vote_count: 10010,
    id: 238,
    video: false,
    vote_average: 8.6,
    title: "The Godfather",
    popularity: 28.948,
    poster_path: "/rPdtLWNsZmAtoZl9PK7S2wE3qiS.jpg",
    original_language: "en",
    original_title: "The Godfather",
    genre_ids: [18, 80],
    backdrop_path: "/6xKCYgH16UuwEGAyroLU6p8HLIn.jpg",
    adult: false,
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    release_date: "1972-03-14"
  },
  {
    vote_count: 4141,
    id: 372058,
    video: false,
    vote_average: 8.6,
    title: "Your Name.",
    popularity: 23.102,
    poster_path: "/xq1Ugd62d23K2knRUx6xxuALTZB.jpg",
    original_language: "ja",
    original_title: "君の名は。",
    genre_ids: [10749, 16, 18],
    backdrop_path: "/nvsdKYPKwf51EAgC0xLJMB9kUZM.jpg",
    adult: false,
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    release_date: "2016-08-26"
  },
  {
    vote_count: 8050,
    id: 424,
    video: false,
    vote_average: 8.5,
    title: "Schindler's List",
    popularity: 26.083,
    poster_path: "/yPisjyLweCl1tbgwgtzBCNCBle.jpg",
    original_language: "en",
    original_title: "Schindler's List",
    genre_ids: [18, 36, 10752],
    backdrop_path: "/af98P1bc7lJsFjhHOVWXQgNNgSQ.jpg",
    adult: false,
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    release_date: "1993-12-15"
  },
  {
    vote_count: 5857,
    id: 240,
    video: false,
    vote_average: 8.5,
    title: "The Godfather: Part II",
    popularity: 23.518,
    poster_path: "/bVq65huQ8vHDd1a4Z37QtuyEvpA.jpg",
    original_language: "en",
    original_title: "The Godfather: Part II",
    genre_ids: [18, 80],
    backdrop_path: "/gLbBRyS7MBrmVUNce91Hmx9vzqI.jpg",
    adult: false,
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    release_date: "1974-12-20"
  },
  {
    vote_count: 7408,
    id: 129,
    video: false,
    vote_average: 8.5,
    title: "Spirited Away",
    popularity: 27.2,
    poster_path: "/oRvMaJOmapypFUcQqpgHMZA6qL9.jpg",
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    genre_ids: [16, 10751, 14],
    backdrop_path: "/dUoGxrlUWDwjpzNggKt33uWlOvM.jpg",
    adult: false,
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    release_date: "2001-07-20"
  },
  {
    vote_count: 8274,
    id: 497,
    video: false,
    vote_average: 8.5,
    title: "The Green Mile",
    popularity: 22.949,
    poster_path: "/sOHqdY1RnSn6kcfAHKu28jvTebE.jpg",
    original_language: "en",
    original_title: "The Green Mile",
    genre_ids: [14, 18, 80],
    backdrop_path: "/Rlt20sEbOQKPVjia7lUilFm49W.jpg",
    adult: false,
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    release_date: "1999-12-10"
  },
  {
    vote_count: 6596,
    id: 299534,
    video: false,
    vote_average: 8.5,
    title: "Avengers: Endgame",
    popularity: 142.453,
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    original_language: "en",
    original_title: "Avengers: Endgame",
    genre_ids: [12, 878, 28],
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    adult: false,
    overview:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    release_date: "2019-04-24"
  },
  {
    vote_count: 7253,
    id: 637,
    video: false,
    vote_average: 8.4,
    title: "Life Is Beautiful",
    popularity: 17.167,
    poster_path: "/f7DImXDebOs148U4uPjI61iDvaK.jpg",
    original_language: "it",
    original_title: "La vita è bella",
    genre_ids: [35, 18],
    backdrop_path: "/bORe0eI72D874TMawOOFvqWS6Xe.jpg",
    adult: false,
    overview:
      "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
    release_date: "1997-12-20"
  },
  {
    vote_count: 15225,
    id: 680,
    video: false,
    vote_average: 8.4,
    title: "Pulp Fiction",
    popularity: 30.347,
    poster_path: "/dM2w364MScsjFf8pfMbaWUcWrR.jpg",
    original_language: "en",
    original_title: "Pulp Fiction",
    genre_ids: [53, 80],
    backdrop_path: "/4cDFJr4HnXN5AdPw4AKrmLlMWdO.jpg",
    adult: false,
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    release_date: "1994-09-10"
  },
  {
    vote_count: 4007,
    id: 324857,
    video: false,
    vote_average: 8.4,
    title: "Spider-Man: Into the Spider-Verse",
    popularity: 65.09,
    poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    original_language: "en",
    original_title: "Spider-Man: Into the Spider-Verse",
    genre_ids: [28, 12, 16, 878, 35],
    backdrop_path: "/uUiId6cG32JSRI6RyBQSvQtLjz2.jpg",
    adult: false,
    overview:
      'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
    release_date: "2018-12-07"
  },
  {
    vote_count: 18881,
    id: 155,
    video: false,
    vote_average: 8.4,
    title: "The Dark Knight",
    popularity: 40.269,
    poster_path: "/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg",
    original_language: "en",
    original_title: "The Dark Knight",
    genre_ids: [18, 28, 80, 53],
    backdrop_path: "/hqkIcbrOHL86UncnHIsHVcVmzue.jpg",
    adult: false,
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    release_date: "2008-07-16"
  },
  {
    vote_count: 14790,
    id: 13,
    video: false,
    vote_average: 8.4,
    title: "Forrest Gump",
    popularity: 25.674,
    poster_path: "/yE5d3BUhE8hCnkMUJOo1QDoOGNz.jpg",
    original_language: "en",
    original_title: "Forrest Gump",
    genre_ids: [35, 18, 10749],
    backdrop_path: "/wMgbnUVS9wbRGAdki8fqxKU1O0N.jpg",
    adult: false,
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    release_date: "1994-07-06"
  },
  {
    vote_count: 16296,
    id: 550,
    video: false,
    vote_average: 8.4,
    title: "Fight Club",
    popularity: 30.946,
    poster_path: "/adw6Lq9FiC9zjYEpOqfq03ituwp.jpg",
    original_language: "en",
    original_title: "Fight Club",
    genre_ids: [18],
    backdrop_path: "/mMZRKb3NVo5ZeSPEIaNW9buLWQ0.jpg",
    adult: false,
    overview:
      'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    release_date: "1999-10-15"
  },
  {
    vote_count: 4931,
    id: 539,
    video: false,
    vote_average: 8.4,
    title: "Psycho",
    popularity: 18.359,
    poster_path: "/81d8oyEFgj7FlxJqSDXWr8JH8kV.jpg",
    original_language: "en",
    original_title: "Psycho",
    genre_ids: [27, 18],
    backdrop_path: "/3md49VBCeqY6MSNyAVY6d5eC6bA.jpg",
    adult: false,
    overview:
      "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother. The place seems quirky, but fine… until Marion decides to take a shower.",
    release_date: "1960-06-16"
  },
  {
    vote_count: 13170,
    id: 122,
    video: false,
    vote_average: 8.4,
    title: "The Lord of the Rings: The Return of the King",
    popularity: 36.614,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    genre_ids: [12, 14, 28],
    backdrop_path: "/8BPZO0Bf8TeAy8znF43z8soK3ys.jpg",
    adult: false,
    overview:
      "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam bring the ring closer to the heart of Mordor, the dark lord's realm.",
    release_date: "2003-12-01"
  },
  {
    vote_count: 2238,
    id: 311,
    video: false,
    vote_average: 8.4,
    title: "Once Upon a Time in America",
    popularity: 16.106,
    poster_path: "/fqP3Q7DWMFqW7mh11hWXbNwN9rz.jpg",
    original_language: "en",
    original_title: "Once Upon a Time in America",
    genre_ids: [18, 80],
    backdrop_path: "/vnT6HzjLSDrAweHn9xWykb8Ii6T.jpg",
    adult: false,
    overview:
      "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
    release_date: "1984-05-23"
  },
  {
    vote_count: 440,
    id: 40096,
    video: false,
    vote_average: 8.4,
    title: "A Dog's Will",
    popularity: 10.745,
    poster_path: "/uHEmM49YphluJnGep8Ef1qwD2QX.jpg",
    original_language: "pt",
    original_title: "O Auto da Compadecida",
    genre_ids: [12, 35],
    backdrop_path: "/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg",
    adult: false,
    overview:
      "The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small Northeast Brazil town. But when they die, they have to be judged by Christ, the Devil and the Virgin Mary, before they are admitted to paradise.",
    release_date: "2000-09-15"
  },
  {
    vote_count: 324,
    id: 517814,
    video: false,
    vote_average: 8.4,
    title: "Capernaum",
    popularity: 22.626,
    poster_path: "/mFnfTVADj8yOxwzprYOmTPselk8.jpg",
    original_language: "ar",
    original_title: "کفرناحوم",
    genre_ids: [18],
    backdrop_path: "/zOKXsgIOaWLotZOBYopPxUkXfuF.jpg",
    adult: false,
    overview:
      "Zain, a 12-year-old boy scrambling to survive on the streets of Beirut, sues his parents for having brought him into such an unjust world, where being a refugee with no documents means that your rights can easily be denied.",
    release_date: "2018-10-06"
  },
  {
    vote_count: 316,
    id: 18491,
    video: false,
    vote_average: 8.4,
    title: "Neon Genesis Evangelion: The End of Evangelion",
    popularity: 9.929,
    poster_path: "/5JYzfyKBwReaQ41WFhqXgOZnPWV.jpg",
    original_language: "ja",
    original_title: "新世紀エヴァンゲリオン劇場版 THE END OF EVANGELION",
    genre_ids: [18, 878, 16],
    backdrop_path: "/AfyuI3glMCBDFmNPj9PY6DwbgGp.jpg",
    adult: false,
    overview:
      "The second of two theatrically released follow-ups to the Neon Genesis Evangelion series. Comprising of two alternate episodes which were first intended to take the place of episodes 25 and 26, this finale answers many of the questions surrounding the series, while also opening up some new possibilities.",
    release_date: "1997-07-19"
  },
  {
    vote_count: 1738,
    id: 11216,
    video: false,
    vote_average: 8.4,
    title: "Cinema Paradiso",
    popularity: 10.792,
    poster_path: "/hYzCLju3W74nLhhRXfPkwDi1Tun.jpg",
    original_language: "it",
    original_title: "Nuovo Cinema Paradiso",
    genre_ids: [18, 10749],
    backdrop_path: "/tVi83ttAeyMJinYpy6xfgJSpzvP.jpg",
    adult: false,
    overview:
      "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
    release_date: "1988-11-17"
  },
  {
    vote_count: 5610,
    id: 769,
    video: false,
    vote_average: 8.4,
    title: "GoodFellas",
    popularity: 19.691,
    poster_path: "/pwpGfTImTGifEGgLb3s6LRPd4I6.jpg",
    original_language: "en",
    original_title: "GoodFellas",
    genre_ids: [18, 80],
    backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
    adult: false,
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    release_date: "1990-09-12"
  },
  {
    vote_count: 5470,
    id: 510,
    video: false,
    vote_average: 8.4,
    title: "One Flew Over the Cuckoo's Nest",
    popularity: 18.391,
    poster_path: "/2Sns5oMb356JNdBHgBETjIpRYy9.jpg",
    original_language: "en",
    original_title: "One Flew Over the Cuckoo's Nest",
    genre_ids: [18],
    backdrop_path: "/4E7YQcwui0PfNXguf4V2X8YocPC.jpg",
    adult: false,
    overview:
      "While serving time for insanity at a state mental hospital, implacable rabble-rouser, Randle Patrick McMurphy, inspires his fellow patients to rebel against the authoritarian rule of head nurse, Mildred Ratched.",
    release_date: "1975-11-18"
  },
  {
    vote_count: 4044,
    id: 429,
    video: false,
    vote_average: 8.4,
    title: "The Good, the Bad and the Ugly",
    popularity: 17.888,
    poster_path: "/wfPHdfofBD5PN96dV96a51B3Ja2.jpg",
    original_language: "it",
    original_title: "Il buono, il brutto, il cattivo",
    genre_ids: [37],
    backdrop_path: "/xGC2fY5KFmtuXnsuQwYQKFOLZFy.jpg",
    adult: false,
    overview:
      "While the Civil War rages between the Union and the Confederacy, three men – a quiet loner, a ruthless hit man and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    release_date: "1966-12-23"
  },
  {
    vote_count: 3721,
    id: 389,
    video: false,
    vote_average: 8.4,
    title: "12 Angry Men",
    popularity: 16.097,
    poster_path: "/3W0v956XxSG5xgm7LB6qu8ExYJ2.jpg",
    original_language: "en",
    original_title: "12 Angry Men",
    genre_ids: [18],
    backdrop_path: "/lH2Ga8OzjU1XlxJ73shOlPx6cRw.jpg",
    adult: false,
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    release_date: "1957-03-25"
  },
  {
    vote_count: 233,
    id: 26451,
    video: false,
    vote_average: 6.9,
    title: "Investigation of a Citizen Above Suspicion",
    popularity: 6.577,
    poster_path: "/uGQV8KYXWbTzJT80Hwe9DXYR3F0.jpg",
    original_language: "it",
    original_title: "Indagine su un cittadino al di sopra di ogni sospetto",
    genre_ids: [18, 80],
    backdrop_path: "/tJaeWoH1UJPyeIU2yd9YJgeghFC.jpg",
    adult: false,
    overview:
      "A chief of detectives, homicide section, kills his mistress and deliberately leaves clues to prove his own responsibility for the crime",
    release_date: "1970-11-13"
  }
];
